name = "SovovaMulti"
uuid = "0cf59ef5-fec3-4aea-9b72-567761fff152"
version = "1.0.0-DEV"
authors = ["Leandro Martinez <lmartine@unicamp.br> and contributors"]

[deps]
PRIMA = "0a7d04aa-8ac2-47b3-b7a7-9dbd6ad661ed"

[compat]
PRIMA = "0.2"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
